### ISSUE TITLE
Seqlevels missing in provided segmentation error

### ISSUE THREAD

**Issue by boyangzhao** [lima1/PureCN#203] opened 2021-10-10 17:46 UTC
Hi Markus,

I encountered an error from PureCN `Seqlevels missing in provided segmentation: Y`. I'm not sure if this has to do with these samples being female, and somehow it's looking for Y chr?

Bo

```
INFO [2021-10-03 07:35:24] ------------------------------------------------------------
INFO [2021-10-03 07:35:24] PureCN 1.99.32
INFO [2021-10-03 07:35:24] ------------------------------------------------------------
INFO [2021-10-03 07:35:24] Arguments: -normal.coverage.file  -tumor.coverage.file tumor.cnr -log.ratio  -seg.file tumor.seg -vcf.file mutect.vcf.gz -normalDB  -genome hg38 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf NULL -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid Tumor -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file  -min.logr.sdev 0.15 -max.segments 300 -plot.cnv TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file  -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model beta -post.optimize FALSE -BPPARAM  -log.file ./purecn.log -args.filterVcf <data> -fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2021-10-03 07:35:24] Loading coverage files...
INFO [2021-10-03 07:35:28] Found log2-ratio in tumor coverage data.
WARN [2021-10-03 07:35:28] log2-ratio contains outliers < -8, ignoring them...
INFO [2021-10-03 07:35:30] Mean coverages: chrX: 468.76, chrY: 11.34, chr1-22: 391.84.
INFO [2021-10-03 07:35:30] Mean coverages: chrX: 468.76, chrY: 11.34, chr1-22: 391.84.
INFO [2021-10-03 07:35:30] Removing 979 intervals with missing log.ratio.
INFO [2021-10-03 07:35:30] Using 236196 intervals (198747 on-target, 37449 off-target).
INFO [2021-10-03 07:35:30] Ratio of mean on-target vs. off-target read counts: NaN
INFO [2021-10-03 07:35:30] Mean off-target bin size: 59748
INFO [2021-10-03 07:35:30] Loading VCF...
INFO [2021-10-03 07:35:38] Found 179162 variants in VCF file.
INFO [2021-10-03 07:35:39] Removing 18893 triallelic sites.
WARN [2021-10-03 07:35:39] Found GERMQ info field with Phred scaled germline probabilities.
WARN [2021-10-03 07:35:40] vcf.file has no DB info field for membership in germline databases. Found and used somatic status instead.
INFO [2021-10-03 07:35:40] 137343 (85.7%) variants annotated as likely germline (DB INFO flag).
WARN [2021-10-03 07:35:44] Found 16699 variants with missing allelic fraction starting with 1:15903_G/GC. Removing them.
INFO [2021-10-03 07:35:46] Tumor is tumor in VCF file.
INFO [2021-10-03 07:35:48] 709 homozygous and 1141 heterozygous variants on chrX.
INFO [2021-10-03 07:35:48] Sex from VCF: F (Fisher's p-value: 0.24, odds-ratio: 0.94).
INFO [2021-10-03 07:35:48] Detected MuTect2 VCF.
INFO [2021-10-03 07:35:49] Removing 52221 Mutect2 calls due to blacklisted failure reasons.
INFO [2021-10-03 07:35:49] Removing 47560 non heterozygous (in matched normal) germline SNPs.
INFO [2021-10-03 07:35:52] Initial testing for significant sample cross-contamination: unlikely
INFO [2021-10-03 07:35:53] Removing 586 variants with AF < 0.030 or AF >= 1.000 or less than 5 supporting reads or depth < 15.
WARN [2021-10-03 07:35:53] Variant ids contain NAs at filter step BQ.
INFO [2021-10-03 07:35:53] Removing 0 low quality variants with BQ < 25.
INFO [2021-10-03 07:35:53] Total size of targeted genomic region: 43.81Mb (61.03Mb with 50bp padding).
INFO [2021-10-03 07:35:54] 11.4% of targets contain variants.
INFO [2021-10-03 07:35:54] Removing 18285 variants outside intervals.
INFO [2021-10-03 07:35:54] Found SOMATIC annotation in VCF.
INFO [2021-10-03 07:35:54] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2021-10-03 07:35:55] Found SOMATIC annotation in VCF. Setting mapping bias to 0.985.
INFO [2021-10-03 07:35:55] Excluding 449 novel or poor quality variants from segmentation.
INFO [2021-10-03 07:35:55] Sample sex: F
INFO [2021-10-03 07:35:55] Segmenting data...
INFO [2021-10-03 07:35:55] Loaded provided segmentation file tumor.seg (format DNAcopy).
WARN [2021-10-03 07:35:55] Provided sampleid (Tumor) does not match tumor found in segmentation.
INFO [2021-10-03 07:35:55] Re-centering provided segment means (offset -0.1515).
INFO [2021-10-03 07:35:55] Setting prune.hclust.h parameter to 0.150000.
FATAL [2021-10-03 07:35:55] Seqlevels missing in provided segmentation: Y 

FATAL [2021-10-03 07:35:55]  

FATAL [2021-10-03 07:35:55] This is most likely a user error due to invalid input data or 

FATAL [2021-10-03 07:35:55] parameters (PureCN 1.99.32). 
```

**Comment by lima1** [comment] 2021-10-10 17:56
Hah, looks like I broke it with my fix to your toy example! Will make sure that this test ignores sex chromosomes. Thanks for reporting.

**Comment by lima1** [comment] 2021-10-11 14:53
Should be fixed now, @boyangzhao

**Comment by lima1** [comment] 2021-10-14 12:48
Closing now, let me know when you find more issues.

**Closed as completed by lima1** 2021-10-14 12:48 UTC
Labels: bug

**Comment by paulafpritchett** [comment] 2022-02-09 18:22
Hi Margus,

I'm afraid that I have encountered a problem similar to the one described above:

----

INFO [2022-02-09 15:08:42] ------------------------------------------------------------
INFO [2022-02-09 15:08:42] PureCN 2.0.1
INFO [2022-02-09 15:08:42] ------------------------------------------------------------
INFO [2022-02-09 15:08:42] Arguments: -normal.coverage.file -tumor.coverage.file /shared/pipeline-user/run_data/indel_samples_pfp/work/RunBcbio/sample_sheet/f
inal/sample1/sample1-cnvkit.cnr -log.ratio -seg.file /shared/pipeline-user/run_data/indel_samples_pfp/work/RunPureCN/30004829_30004829
01/sample1.seg -vcf.file /shared/pipeline-user/run_data/indel_samples_pfp/work/RunBcbio/sample_sheet/final/2020-09-29_tumor_only/30004829_300048290
1-mutect2-annotated.vcf.gz -normalDB -genome hg38 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf /shared/pipeline-user/support/mapping_bias/pon_purecn_map
ping_bias_v2.rds -args.filterIntervals 100,0.05 -args.segmentation 0.005,NULL, -sampleid sample1 -min.ploidy 1.4 -max.ploidy 6 -max.non.clonal 0.2
-max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file -min.logr.sdev 0.15 -max.segments 300 -plot.cnv
TRUE -vcf.field.prefix PureCN. -cosmic.vcf.file -DB.info.flag DB -POPAF.info.field POP_AF -Cosmic.CNT.info.field Cosmic.CNT -model beta -post.optimize TRUE -
log.file /shared/pipeline-user/run_data/indel_samples_pfp/work/RunPureCN/sample1/sample1.log -args.filterVcf <data> -fun.segmentation <
data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data> -BPPARAM <data>
INFO [2022-02-09 15:08:42] Using BiocParallel for parallel optimization.
INFO [2022-02-09 15:08:42] Loading coverage files...
INFO [2022-02-09 15:08:46] Found log2-ratio in tumor coverage data.
WARN [2022-02-09 15:08:46] log2-ratio contains outliers < -8, ignoring them...
INFO [2022-02-09 15:08:47] Mean coverages: chrX: 179.77, chrY: 102.75, chr1-22: 252.33.
INFO [2022-02-09 15:08:47] Mean coverages: chrX: 179.77, chrY: 102.75, chr1-22: 252.33.
INFO [2022-02-09 15:08:47] Removing 7 intervals with missing log.ratio.
INFO [2022-02-09 15:08:47] Using 239223 intervals (232526 on-target, 6697 off-target).
INFO [2022-02-09 15:08:47] Ratio of mean on-target vs. off-target read counts: NaN
INFO [2022-02-09 15:08:47] Mean off-target bin size: 263672
INFO [2022-02-09 15:08:47] Loading VCF...
INFO [2022-02-09 15:08:56] Found 95868 variants in VCF file.
INFO [2022-02-09 15:08:57] Removing 3417 triallelic sites.
WARN [2022-02-09 15:08:57] VCF contains both DB and POPAF INFO fields. Will ignore POPAF.
INFO [2022-02-09 15:08:57] 47844 (51.8%) variants annotated as likely germline (DB INFO flag).
INFO [2022-02-09 15:09:00] sample1 is tumor in VCF file.
INFO [2022-02-09 15:09:01] 597 homozygous and 120 heterozygous variants on chrX.
INFO [2022-02-09 15:09:01] Sex from VCF: M (Fisher's p-value: < 0.0001, odds-ratio: 8.16).
INFO [2022-02-09 15:09:01] Detected MuTect2 VCF.
INFO [2022-02-09 15:09:02] Removing 27491 Mutect2 calls due to blacklisted failure reasons.
INFO [2022-02-09 15:09:05] Initial testing for significant sample cross-contamination: unlikely
INFO [2022-02-09 15:09:06] Removing 29658 variants with AF < 0.030 or AF >= 0.970 or less than 5 supporting reads or depth < 15.
WARN [2022-02-09 15:09:06] Variant ids contain NAs at filter step BQ.
INFO [2022-02-09 15:09:07] Removing 0 low quality variants with BQ < 25.
INFO [2022-02-09 15:09:07] Total size of targeted genomic region: 36.30Mb (55.73Mb with 50bp padding).
INFO [2022-02-09 15:09:07] 10.2% of targets contain variants.
INFO [2022-02-09 15:09:08] Removing 9805 variants outside intervals.
INFO [2022-02-09 15:09:08] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2022-02-09 15:09:08] Loading mapping bias file pon_purecn_mapping_bias_v2.rds...
INFO [2022-02-09 15:09:08] Found 232831 variants in mapping bias file.
INFO [2022-02-09 15:09:09] Imputing mapping bias for 3815 variants...
INFO [2022-02-09 15:10:01] Excluding 5113 novel or poor quality variants from segmentation.
INFO [2022-02-09 15:10:01] Excluding 3815 variants not in pool of normals from segmentation.
INFO [2022-02-09 15:10:01] Sample sex: M
INFO [2022-02-09 15:10:01] Segmenting data...
INFO [2022-02-09 15:10:01] Loaded provided segmentation file sample1.seg (format DNAcopy).
WARN [2022-02-09 15:10:01] Provided sampleid (sample1) does not match sample1-cnvkit found in segmentation.
INFO [2022-02-09 15:10:01] Re-centering provided segment means (offset 0.0120).
INFO [2022-02-09 15:10:02] Loading pre-computed boundaries for DNAcopy...
INFO [2022-02-09 15:10:02] Setting undo.SD parameter to 0.750000.
INFO [2022-02-09 15:10:02] Loading pre-computed boundaries for DNAcopy...
INFO [2022-02-09 15:10:02] Setting undo.SD parameter to 0.750000.
INFO [2022-02-09 15:10:28] Setting prune.hclust.h parameter to 0.200000.
FATAL [2022-02-09 15:10:29] Seqlevels missing in provided segmentation:
FATAL [2022-02-09 15:10:29] chr7_KI270803v1_alt,chr17_KI270909v1_alt
FATAL [2022-02-09 15:10:29]
FATAL [2022-02-09 15:10:29] This is most likely a user error due to invalid input data or
FATAL [2022-02-09 15:10:29] parameters (PureCN 2.0.1).

----


This error seems to be specific to this release (PureCN 2.0.1), as I have run the same sample using an older version (PureCN 1.22.1) and it worked fine.
Do you think you could help me with this?
Alternatively, perhaps there is a flag to exclude chromosome scaffolds?

Thank you for your help,
Paula

**Comment by paulafpritchett** [comment] 2022-02-10 09:28
Hi Markus,

Thank you for the quick reply.
 chr7_KI270803v1_alt and chr17_KI270909v1_alt
It's present on both the vcf file as in the CNVkit segmentation file.
Would you like to have a look at those files?

Many thanks,
Paula

**Comment by paulafpritchett** [comment] 2022-02-10 16:45
Hi Margus,

I can share the files via email, no problem. I'll send it to markus<dot>riester<at>novartis<dot>com, is that ok?

Thank you,
Paula

**Comment by GeertvanGeest** [comment] 2024-11-18 07:13
How did you solve this issue in the end? I'm having similar issues, while trying to run PureCN for dog tumors:

```
INFO [2024-11-14 13:24:23] Imputing mapping bias for 13 variants...
INFO [2024-11-14 13:24:24] Excluding 6 novel or poor quality variants from segmentation.
INFO [2024-11-14 13:24:24] Sample sex: ?
INFO [2024-11-14 13:24:24] Segmenting data...
INFO [2024-11-14 13:24:24] Loaded provided segmentation file 51407_T.seg (format DNAcopy).
INFO [2024-11-14 13:24:24] Re-centering provided segment means (offset 0.3089).
INFO [2024-11-14 13:24:24] Setting prune.hclust.h parameter to 0.150000.
FATAL [2024-11-14 13:24:25] Seqlevels missing in provided segmentation: 23,24 
```

This is my command:

```bash
Rscript $PURECN/PureCN.R \
--out "$OUTDIR" \
--sampleid "$PATIENT"_T \
--tumor "$OUTDIR"/"$PATIENT"_T.cnr \
--seg-file "$OUTDIR"/"$PATIENT"_T.seg \
--vcf "$OUTDIR"/"$PATIENT"_mutect2_renamed.vcf.gz \
--stats-file "$MUTECT_DIR"/"$PATIENT"_T_vs_"$PATIENT"_N.mutect2.vcf.gz.stats \
--mapping-bias-file "$NORMAL_DIR"/mapping_bias_UU_Cfam_GSD_1.0_canFam4.rds \
--genome UU_Cfam_GSD_1.0_canFam4 \
--fun-segmentation Hclust \
--force --post-optimize \
--cores "$SLURM_CPUS_PER_TASK"
```

And I created the `.seg` file based on a CNVkit `.cns` file:

```bash
cnvkit.py export seg \
"$PROJDIR"/pipelines/sarek/results/combined_b1_b2_E_cnv/variant_calling/cnvkit/"$PATIENT"_T_vs_"$PATIENT"_N/"$PATIENT"_T.cns \
--enumerate-chroms \
-o "$OUTDIR"/"$PATIENT"_T.seg
```

And `mapping_bias_UU_Cfam_GSD_1.0_canFam4.rds` with:

```bash
Rscript $PURECN/NormalDB.R \
--out-dir "$OUTDIR" \
--genome UU_Cfam_GSD_1.0_canFam4 \
--normal-panel "$PROJDIR"/downstream_analyses/purecn/normals_renamed.vcf.gz \
--force
```

All chromosome names are integers (except sex chromosomes) in all the input files (`. cnr`, `.seg`, `.vcf.gz`). Chromosome 23 and 24 are present in all input files, including in the `GRanges` object in `mapping_bias_UU_Cfam_GSD_1.0_canFam4.rds`.

**Comment by lima1** [comment] 2024-11-18 17:56
Thanks @GeertvanGeest . I actually cannot remember what the issue was. I haven't really tested it with non-human data. It should work though, so happy to debug if you can send a minimal example to reproduce the error. Email me and I can send a OneDrive link if too large for attachment.

**Comment by GeertvanGeest** [comment] 2024-11-19 06:57
Thanks for your response @lima1 ! I'll prepare a minimal example.
