### ISSUE TITLE
error running Rscript PureCN.R

### ISSUE THREAD

**Issue by bosmont** [lima1/PureCN#129] opened 2020-07-14 16:59 UTC
Hi, I started using PureCN recently and run into a problem.  When running the following command:
Rscript ~/R4.0.0/lib/R/library/PureCN/extdata/PureCN.R -i sampleid
            --tumor tumor.normcov.file
            --vcf vcf.file
            --normaldb, normdb
            --genome hg19
            --snpblacklist ../hg19_simpleRepeats.bed
            --mappingbiasfile ../mapping_bias.rds
            --out sampleid
            --postoptimize TRUE
            --intervals targets.filter.txt

It run to step of "Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.", then the following error:
"Error in mergeNamedAtomicVectors(genome(x), genome(y), what = c("sequence",  : 
  sequences 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X, Y, MT, GL000207.1, GL000226.1, GL000229.1, GL000231.1, GL000210.1, GL000239.1, GL000235.1, GL000201.1, GL000247.1, GL000245.1, GL000197.1, GL000203.1, GL000246.1, GL000249.1, GL000196.1, GL000248.1, GL000244.1, GL000238.1, GL000202.1, GL000234.1, GL000232.1, GL000206.1, GL000240.1, GL000236.1, GL000241.1, GL000243.1, GL000242.1, GL000230.1, GL000237.1, GL000233.1, GL000204.1, GL000198.1, GL000208.1, GL000191.1, GL000227.1, GL000228.1, GL000214.1, GL000221.1, GL000209.1, GL000218.1, GL000220.1, GL000213.1, GL000211.1, GL000199.1, GL000217.1, GL000216.1, GL000215.1, GL000205.1, GL000219.1, GL000224.1, GL000223.1, GL000195.1, GL000212.1, GL000222.1, GL000200.1, GL000193.1, GL000194.1, GL000225.1, GL000192.1 have incompatible genomes:
  - in 'x': hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, hg19, h
Calls: runAbsoluteCN ... .Seqinfo.merge -> .Seqinfo.mergexy -> mergeNamedAtomicVectors
Execution halted"

I understand PureCN uses library(VariantAnnotation) to read the VCF file.  could you let me know what are the x and y in genome(x), genome(y)?  I guess one of them is vcf, not sure about the other one.  

Thanks a lot for your help.

**Comment by lima1** [comment] 2020-07-14 17:57
Hi, can you post the complete output of the log files + the output of sessionInfo()? 

I think those kind of errors should have been fixed in recent versions. So try updating to the latest 1.18 if you are not there already.

**Comment by bosmont** [comment] 2020-07-14 18:52
Thanks for the quick response.  **Below is the log file:**

INFO [2020-07-14 12:47:14] ------------------------------------------------------------
INFO [2020-07-14 12:47:14] PureCN 1.19.6
INFO [2020-07-14 12:47:14] ------------------------------------------------------------
INFO [2020-07-14 12:47:14] Arguments: -tumor.coverage.file /home/ghost/work/invitae/var_reduction/purecn/ontarget_nobackbone/INSF775714.normalizedCov.txt -log.ratio  -seg.file  -vcf.f
ile INSF775714.vcf -genome hg19 -sex ? -args.setPriorVcf 6 -args.setMappingBiasVcf ../mapping_bias.rds -args.segmentation NULL,0.005,NULL -sampleid INSF775714 -min.ploidy 1 -max.ploid
y 6 -max.non.clonal 0.2 -max.homozygous.loss 0.05,1e+07 -log.ratio.calibration 0.1 -model.homozygous FALSE -error 0.001 -interval.file targets.filter.txt -max.segments 300 -plot.cnv T
RUE -DB.info.flag DB -POPAF.info.field POP_AF -model beta -post.optimize FALSE -BPPARAM  -log.file INSF775714.log -normal.coverage.file <data> -normalDB <data> -args.filterVcf <data> 
-fun.segmentation <data> -test.num.copy <data> -test.purity <data> -speedup.heuristics <data>
INFO [2020-07-14 12:47:14] Loading coverage files...
INFO [2020-07-14 12:47:14] Mean target coverages: 385X (tumor) 366X (normal).
INFO [2020-07-14 12:47:14] Mean coverages: chrX: 350.89, chrY: 0.67, chr1-22: 364.65.
INFO [2020-07-14 12:47:14] Mean coverages: chrX: 345.94, chrY: 0.67, chr1-22: 363.91.
INFO [2020-07-14 12:47:15] Removing 39 intervals with missing log.ratio.
INFO [2020-07-14 12:47:15] Removing 43 intervals excluded in normalDB.
INFO [2020-07-14 12:47:15] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2020-07-14 12:47:15] Using 11167 intervals (11167 on-target, 0 off-target).
INFO [2020-07-14 12:47:15] No off-target intervals. If this is hybrid-capture data, consider adding them.
INFO [2020-07-14 12:47:15] AT/GC dropout: 1.03 (tumor), 0.96 (normal). 
INFO [2020-07-14 12:47:15] Loading VCF...
INFO [2020-07-14 12:47:19] Found 466276 variants in VCF file.
INFO [2020-07-14 12:47:20] 317995 (68.2%) variants annotated as likely germline (DB INFO flag).
INFO [2020-07-14 12:47:20] INSF775714 is tumor in VCF file.
INFO [2020-07-14 12:47:21] 74 homozygous and 264 heterozygous variants on chrX.
INFO [2020-07-14 12:47:21] Sex from VCF: F (Fisher's p-value: 0.019, odds-ratio: 0.73).
INFO [2020-07-14 12:47:33] Initial testing for significant sample cross-contamination: maybe
INFO [2020-07-14 12:47:33] Removing 454126 variants with AF < 0.030 or AF >= 0.970 or less than 3 supporting reads or depth < 15.
INFO [2020-07-14 12:47:37] Removing 0 blacklisted variants.
INFO [2020-07-14 12:47:37] Removing 218 low quality variants with BQ < 25.
INFO [2020-07-14 12:47:37] Total size of targeted genomic region: 3.15Mb (3.99Mb with 50bp padding).
INFO [2020-07-14 12:47:38] 19.0% of targets contain variants.
INFO [2020-07-14 12:47:38] Removing 9292 variants outside intervals.
INFO [2020-07-14 12:47:38] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.

**And the session info:**

R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /home/ghost/R4.0.0/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] PureCN_1.19.6               VariantAnnotation_1.34.0    Rsamtools_2.4.0             Biostrings_2.56.0           XVector_0.28.0             
 [6] SummarizedExperiment_1.18.2 DelayedArray_0.14.0         matrixStats_0.56.0          Biobase_2.48.0              GenomicRanges_1.40.0       
[11] GenomeInfoDb_1.24.2         IRanges_2.22.2              S4Vectors_0.26.1            BiocGenerics_0.34.0         DNAcopy_1.62.0             

loaded via a namespace (and not attached):
 [1] bitops_1.0-6             bit64_0.9-7              RColorBrewer_1.1-2       progress_1.2.2           httr_1.4.1              
 [6] rprojroot_1.3-2          tools_4.0.0              backports_1.1.8          R6_2.4.1                 DBI_1.1.0               
[11] colorspace_1.4-1         withr_2.2.0              tidyselect_1.1.0         gridExtra_2.3            prettyunits_1.1.1       
[16] processx_3.4.3           bit_1.1-15.2             curl_4.3                 compiler_4.0.0           cli_2.0.2               
[21] formatR_1.7              rtracklayer_1.48.0       scales_1.1.1             callr_3.4.3              askpass_1.1             
[26] rappdirs_0.3.1           stringr_1.4.0            digest_0.6.25            pkgconfig_2.0.3          dbplyr_1.4.4            
[31] BSgenome_1.56.0          rlang_0.4.7              rstudioapi_0.11          RSQLite_2.2.0            VGAM_1.1-3              
[36] generics_0.0.2           BiocParallel_1.22.0      dplyr_1.0.0              RCurl_1.98-1.2           magrittr_1.5            
[41] GenomeInfoDbData_1.2.3   futile.logger_1.4.3      Matrix_1.2-18            Rcpp_1.0.5               munsell_0.5.0           
[46] Rhdf5lib_1.10.1          fansi_0.4.1              lifecycle_0.2.0          stringi_1.4.6            zlibbioc_1.34.0         
[51] rhdf5_2.32.2             pkgbuild_1.1.0           BiocFileCache_1.12.0     grid_4.0.0               blob_1.2.1              
[56] crayon_1.3.4             lattice_0.20-41          splines_4.0.0            GenomicFeatures_1.40.1   hms_0.5.3               
[61] ps_1.3.3                 pillar_1.4.6             biomaRt_2.44.1           futile.options_1.0.1     XML_3.99-0.4            
[66] glue_1.4.1               lambda.r_1.2.4           data.table_1.12.8        remotes_2.1.1            BiocManager_1.30.10     
[71] vctrs_0.3.1              gtable_0.3.0             openssl_1.4.2            purrr_0.3.4              assertthat_0.2.1        
[76] ggplot2_3.3.2            tibble_3.0.3             GenomicAlignments_1.24.0 AnnotationDbi_1.50.1     memoise_1.1.0           
[81] ellipsis_0.3.1

**Comment by lima1** [comment] 2020-07-14 19:16
Thanks a lot, yes, this shouldn't happen. I'll try to figure out where and why this still causes issues.

**Comment by lima1** [comment] 2020-07-14 20:06
Not sure if the --mappingbiasfile is the cause for the crash, but the latest commit does some sanity checks here. Can you checkout and try again?

**Comment by bosmont** [comment] 2020-07-14 23:17
Hi Thanks so much for checking on this.

I removed the --mappingbiasfile  option, the program did went a few steps further, then showed another error.  Below are the last few lines in the log file and the error:

INFO [2020-07-14 17:11:04] Removing 9292 variants outside intervals.
INFO [2020-07-14 17:11:04] Setting somatic prior probabilities for dbSNP hits to 0.000500 or to 0.500000 otherwise.
INFO [2020-07-14 17:11:04] VCF does not contain somatic status. For best results, consider providing mapping.bias.file when matched normals are not available.
INFO [2020-07-14 17:11:04] Excluding 121 novel or poor quality variants from segmentation.
INFO [2020-07-14 17:11:04] Sample sex: F
INFO [2020-07-14 17:11:04] Segmenting data...
Error in (function (normal, tumor, log.ratio, seg, plot.cnv, sampleid,  : 
  unused argument (interval.weight.file = NULL)
Calls: runAbsoluteCN -> do.call
Execution halted

**Comment by lima1** [comment] 2020-07-14 23:32
Sorry, that was unrelated (leftover from a recent cleanup). Can you try again?

Also if you keep --mappingbiasfile, do you still get the error?

**Comment by bosmont** [comment] 2020-07-15 03:43
Hi,  Yes it works now.  Thank you so much for solving the issue so quickly.  Very much appreciated!!

**Closed** 2020-07-15 03:48 UTC
Labels: bug
