### ISSUE TITLE
arguments imply differing number of rows: 0, 1

### ISSUE THREAD

**Issue by milkcookie** [lima1/PureCN#124] opened 2020-05-26 17:18 UTC
Dear all:
when I run PureCN.R with a matched normal sample, there was a error：
Error in data.frame(bias = tmp, shape1 = NA, shape2 = NA) :
arguments imply differing number of rows: 0, 1
Calls: runAbsoluteCN -> do.call -> <Anonymous> -> data.frame
my cmd:
Rscript PureCN.R --out C1905659-r1TB --tumor C1905659-r1TB/C1905659-r1TB.cons_coverage_loess.txt.gz --normal C1905659-r1TB/C1905659-F1WB.cnv_coverage_loess.txt.gz --sampleid C1905659-r1TB --vcf C1905659-r1TB.vcf --normaldb C1905659-r1TB/normalDB_hg19.rds --intervals baits_hg19_intervals.txt --genome hg19

its log:
INFO [2020-05-27 01:06:42] Loading coverage files...
INFO [2020-05-27 01:06:44] Mean target coverages: 2481X (tumor) 1090X (normal).
WARN [2020-05-27 01:06:45] Allosome coverage missing, cannot determine sex.
WARN [2020-05-27 01:06:45] Allosome coverage missing, cannot determine sex.
INFO [2020-05-27 01:06:46] Removing 127 intervals with missing log.ratio.
INFO [2020-05-27 01:06:46] Removing 31 low/high GC targets.
INFO [2020-05-27 01:06:46] Removing 366 intervals excluded in normalDB.
INFO [2020-05-27 01:06:46] Removing 2 intervals with low total coverage in normal (< 150.00 reads).
INFO [2020-05-27 01:06:46] normalDB provided. Setting minimum coverage for segmentation to 0.0015X.
INFO [2020-05-27 01:06:46] Removing 1291 low coverage (< 0.0015X) intervals.
INFO [2020-05-27 01:06:46] Using 22629 intervals (9151 on-target, 13478 off-target).
INFO [2020-05-27 01:06:47] Ratio of mean on-target vs. off-target read counts: 5.03
INFO [2020-05-27 01:06:47] Mean off-target bin size: 192856
INFO [2020-05-27 01:06:48] AT/GC dropout: 1.00 (tumor), 1.00 (normal). 
INFO [2020-05-27 01:06:48] Loading VCF...
INFO [2020-05-27 01:06:48] Found 3887 variants in VCF file.
INFO [2020-05-27 01:06:48] 3550 (91.3%) variants annotated as likely germline (DB INFO flag).
INFO [2020-05-27 01:06:49] C1905659-r1TB is tumor in VCF file.
INFO [2020-05-27 01:06:49] 75 homozygous and 22 heterozygous variants on chrX.
INFO [2020-05-27 01:06:49] Sex from VCF: M (Fisher's p-value: < 0.0001, odds-ratio: 7.32).
INFO [2020-05-27 01:06:49] Removing 3541 non heterozygous (in matched normal) germline SNPs.
INFO [2020-05-27 01:06:50] Initial testing for significant sample cross-contamination: unlikely
INFO [2020-05-27 01:06:50] Removing 1 variants with AF < 0.030 or AF >= 1.000 or less than 6 supporting reads or depth < 15.
INFO [2020-05-27 01:06:50] Removing 0 low quality variants with BQ < 25.
INFO [2020-05-27 01:06:50] Total size of targeted genomic region: 1.82Mb (2.61Mb with 50bp padding).
INFO [2020-05-27 01:06:50] 0.0% of targets contain variants.
INFO [2020-05-27 01:06:50] Removing 345 variants outside intervals.
INFO [2020-05-27 01:06:50] Found SOMATIC annotation in VCF.
INFO [2020-05-27 01:06:50] Setting somatic prior probabilities for somatic variants to 0.999000 or to 0.000100 otherwise.
INFO [2020-05-27 01:06:50] Found SOMATIC annotation in VCF. Setting mapping bias to NaN.
Error in data.frame(bias = tmp, shape1 = NA, shape2 = NA) : 
  arguments imply differing number of rows: 0, 1
Calls: runAbsoluteCN -> do.call -> <Anonymous> -> data.frame
Execution halted

yours 
milk

**Comment by lima1** [comment] 2020-05-26 18:13
Hi Milk,

the issue is that none of the variant pass the heterozygous filter:

`INFO [2020-05-27 01:06:49] Removing 3541 non heterozygous (in matched normal) germline SNPs.`

Can you provide some details how you generated the VCF? If it is GATK4/Mutect2, make sure to run it with --genotype-germline-sites. There were also a few fixed for M2 very recently, only available in the master branch.

Also, if you generated a normalDB, yo do not need to provide a normal coverage file. The normalDB will usually result in a cleaner copy number profile. I might add a feature to take advantage of the normal coverage file AND the normalDB, but for now I would ignore the normal coverage. (Keep running the variant caller with the matched normal though).

Markus

**Comment by milkcookie** [comment] 2020-05-27 01:56
Hi Markus,
thanks for your prompt reply，I will try with your production pipe, its my cmd to generate vcf:
java1.7 -jar -Xmx10G mutect-1.1.7.jar -T MuTect -R hg19.fasta \
--intervals 3900SNP.bed --dbsnp dbsnp146.vcf --cosmic CosmicCodingMuts_no_ChrM.vcf \
-I:normal  normal.bam -I:tumor tumor.bam -o sample.stat.txt -vcf sample.vcf

Milk

**Comment by lima1** [comment] 2020-05-27 02:22
For Mutect 1.1.7, you should be fine with the latest two stable versions (1.16 or 1.18).

The issue seems your --intervals argument. 

What kind of assay are you working with? 

PureCN is made for hybrid capture data and your main intervals should be the capture baits, not SNPs. You can provide Mutect these bait locations, but I would recommend adding a padding with --interval_padding 100.

**Comment by milkcookie** [comment] 2020-05-27 07:42
yes I use version 1.16 here, the interval file is some hot snp pos, ok I will use my interval file. thanks.
I worked with panel data, about 700gene's all exons.

**Comment by lima1** [comment] 2020-05-27 13:13
Great, 700 genes should give you nice results. Feel free to send another log file and I'm more than happy to point you to further improvements where I see them.

**Comment by milkcookie** [comment] 2020-05-27 14:15
Hi, Markus, that's so nice of you, thanks for your help。

**Comment by milkcookie** [comment] 2020-05-28 16:04
Hi Markus. 
I got purity result with PureCN, I think PureCN is a very nice software, the result is better than before , but some results were much different from the test experimental result,
I use about 100 paired sample, do your hava any suggestions to improve the result, just like change some paramaters, thank you very much. 
yours
milk
the cmd:
Rscript $PURECN/PureCN.R --out C1902285-r1TA --tumor C1902285-r1TA.cons_coverage_loess.txt.gz --sampleid C1902285 --vcf C1902285-r1TA.vcf --normaldb normalDB_hg19.rds --intervals 654_baits_hg19_intervals.txt --genome hg19 --padding 100 --mappingbiasfile mapping_bias_hg19.rds --statsfile C1902285-r1TA.txt --force --postoptimize --seed 123
sample | PureCN purity | exp purity(gold std) | delta(abs)
C1905660 | 0.15 | 0.15 | 0
C1908542 | 0.15 | 0.15 | 0
C2000538 | 0.15 | 0.15 | 0
C1905625 | 0.29 | 0.3 | 0.01
C1908589 | 0.74 | 0.75 | 0.01
C1905551 | 0.57 | 0.6 | 0.03
C1905589 | 0.23 | 0.2 | 0.03
C1905621 | 0.23 | 0.2 | 0.03
C1908569 | 0.33 | 0.3 | 0.03
C1905615 | 0.29 | 0.25 | 0.04
C1904991 | 0.15 | 0.1 | 0.05
C1905526 | 0.15 | 0.1 | 0.05
C1905560 | 0.25 | 0.2 | 0.05
C1905597 | 0.15 | 0.1 | 0.05
C1905607 | 0.15 | 0.2 | 0.05
C1905609 | 0.15 | 0.2 | 0.05
C1905648 | 0.15 | 0.2 | 0.05
C1907518 | 0.15 | 0.1 | 0.05
C1907524 | 0.15 | 0.2 | 0.05
C1907530 | 0.15 | 0.1 | 0.05
C1907559 | 0.15 | 0.1 | 0.05
C1908536 | 0.15 | 0.2 | 0.05
C1908540 | 0.15 | 0.2 | 0.05
C1908604 | 0.15 | 0.1 | 0.05
C2000531 | 0.15 | 0.1 | 0.05
C1905516 | 0.16 | 0.1 | 0.06
C1907574 | 0.16 | 0.1 | 0.06
C1908594 | 0.27 | 0.2 | 0.07
C1908590 | 0.33 | 0.25 | 0.08
C1908606 | 0.48 | 0.4 | 0.08
C1905594 | 0.21 | 0.3 | 0.09
C1905527 | 0.15 | 0.05 | 0.1
C1905552 | 0.15 | 0.05 | 0.1
C1905561 | 0.15 | 0.05 | 0.1
C1905622 | 0.15 | 0.05 | 0.1
C1905639 | 0.15 | 0.25 | 0.1
C1905640 | 0.15 | 0.25 | 0.1
C1907532 | 0.3 | 0.2 | 0.1
C1908541 | 0.15 | 0.25 | 0.1
C1908605 | 0.15 | 0.25 | 0.1
C1908624 | 0.15 | 0.25 | 0.1
C1905520 | 0.31 | 0.2 | 0.11
C1905618 | 0.29 | 0.4 | 0.11
C1907512 | 0.16 | 0.05 | 0.11
C1908584 | 0.27 | 0.4 | 0.13
C1902285 | 0.15 | 0.3 | 0.15
C1905600 | 0.15 | 0.3 | 0.15
C1905614 | 0.15 | 0.3 | 0.15
C1907529 | 0.15 | 0.3 | 0.15
C1907533 | 0.15 | 0.3 | 0.15
C1908611 | 0.15 | 0.3 | 0.15
C1908613 | 0.65 | 0.5 | 0.15
C1907543 | 0.24 | 0.4 | 0.16
C1905580 | 0.47 | 0.3 | 0.17
C1905661 | 0.33 | 0.5 | 0.17
C1907537 | 0.29 | 0.1 | 0.19
C1908543 | 0.24 | 0.05 | 0.19
C1905636 | 0.15 | 0.35 | 0.2
C1907548 | 0.25 | 0.05 | 0.2
C1907564 | 0.2 | 0.4 | 0.2
C1907567 | 0.15 | 0.35 | 0.2
C1908546 | 0.15 | 0.35 | 0.2
C1908588 | 0.23 | 0.45 | 0.22
C1908592 | 0.18 | 0.4 | 0.22
C1905577 | 0.32 | 0.55 | 0.23
C1905629 | 0.16 | 0.4 | 0.24
C1905663 | 0.39 | 0.15 | 0.24
C1905521 | 0.15 | 0.4 | 0.25
C1905568 | 0.15 | 0.4 | 0.25
C1908568 | 0.15 | 0.4 | 0.25
C1908570 | 0.64 | 0.9 | 0.26
C2000548 | 0.44 | 0.7 | 0.26
C1905623 | 0.23 | 0.5 | 0.27
C1907581 | 0.27 | 0.55 | 0.28
C1905572 | 0.15 | 0.45 | 0.3
C1907579 | 0.2 | 0.5 | 0.3
C1905562 | 0.36 | 0.05 | 0.31
C1905582 | 0.36 | 0.05 | 0.31
C1905627 | 0.29 | 0.6 | 0.31
C1908544 | 0.29 | 0.6 | 0.31
C1908535 | 0.42 | 0.1 | 0.32
C1905604 | 0.17 | 0.5 | 0.33
C1905610 | 0.38 | 0.05 | 0.33
C1905628 | 0.27 | 0.6 | 0.33
C1905646 | 0.17 | 0.5 | 0.33
C1908595 | 0.36 | 0.7 | 0.34
C1905616 | 0.15 | 0.5 | 0.35
C1905653 | 0.25 | 0.6 | 0.35
C1905659 | 0.15 | 0.5 | 0.35
C1908545 | 0.15 | 0.5 | 0.35
C1908565 | 0.42 | 0.8 | 0.38
C1905590 | 0.31 | 0.7 | 0.39
C1907591 | 0.21 | 0.6 | 0.39
C1905579 | 0.51 | 0.95 | 0.44
C1905553 | 0.75 | 0.3 | 0.45
C1905624 | 0.15 | 0.6 | 0.45
C1905633 | 0.15 | 0.6 | 0.45
C1908576 | 0.15 | 0.6 | 0.45
C1908600 | 0.25 | 0.7 | 0.45
C1905620 | 0.22 | 0.7 | 0.48
C1905635 | 0.22 | 0.7 | 0.48
C1905608 | 0.21 | 0.7 | 0.49
C1907592 | 0.16 | 0.65 | 0.49
C1908560 | 0.16 | 0.65 | 0.49
C1907580 | 0.2 | 0.7 | 0.5
C1905641 | 0.25 | 0.8 | 0.55
C1905664 | 0.15 | 0.7 | 0.55
C1907593 | 0.15 | 0.7 | 0.55
C1905575 | 0.25 | 0.85 | 0.6
C1907540 | 0.19 | 0.8 | 0.61
C1905525 | 0.17 | 0.8 | 0.63
C1907549 | 0.27 | 0.9 | 0.63
C1908566 | 0.22 | 0.85 | 0.63
C1905599 | 0.16 | 0.8 | 0.64
C1905637 | 0.15 | 0.8 | 0.65
C1905652 | 0.17 | 0.9 | 0.73
C1905550 | 0.15 | 0.95 | 0.8

**Comment by lima1** [comment] 2020-05-28 16:28
Can you post the log-file and b-allele frequency plot for C1905550 (Similar to Fig. 4 in https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/PureCN.pdf).

**Comment by milkcookie** [comment] 2020-05-28 16:53
thanks for you reply, the attach is the pdf img file and the log file of C1905550.
[C1905550.log](https://github.com/lima1/PureCN/files/4697121/C1905550.log)
[C1905550_chromosomes.pdf](https://github.com/lima1/PureCN/files/4697122/C1905550_chromosomes.pdf)

**Comment by lima1** [comment] 2020-05-28 16:58
Hi Milk, what samples are those? Looks like there are no copy number events. Are these simulated or pediatric/heme malignancies?

**Comment by milkcookie** [comment] 2020-05-28 17:04
Hi Markus, Its some tumor tissue samples that we got from the hospital. and test in our lab.

**Comment by lima1** [comment] 2020-05-28 17:43
How did you determine the gold standard?

**Comment by milkcookie** [comment] 2020-05-29 01:23
We used pathological section examination to determine the purity.

**Comment by lima1** [comment] 2020-05-29 01:34
Have a look at the samples that are flagged for having no copy number alterations ("NON-ABERRANT").  

Check if they have known hotspot mutations (BRAF, PIK3CA, KRAS etc.)? Are those from cancer types that are exceptionally silent, copy number wise (such as certain heme or pediatric malignancies)? It is very rare to have high purity samples without any copy number events.

Then, the pathology estimates can be very different from the algorithmic estimates, see https://www.nature.com/articles/nbt.2203 (Fig 2e). 

The vignette should provide you an explainer how to check if the PureCN estimates are correct. It's a lot in the beginning, but try to understand the main plots. Feel free to ask questions here and post examples you are unsure.

**Comment by milkcookie** [comment] 2020-05-29 01:58
ok thank you very much, you're the best developor I've ever seen here, I will try to check the result with your suggestions.

**Comment by milkcookie** [comment] 2020-06-02 02:53
Hi markus, I have a new questions, is there any refluences when too many SNV filter is REJECT in somatic vcf file? Does PureCN fiter those REJECT SNV？

**Comment by lima1** [comment] 2020-06-02 03:41
For Mutect 1.1.7 with provided stats file, you should be fine. It will ignore the REJECT flag, instead it will look at the failure reason listed in the stats file and will remove artifacts while keeping germline.

You can always compare the input VCF with the output variants (either _variants.csv or .vcf.gz if you provided --vcf) to see which variants were removed. Note that variants labelled as flagged by PureCN are ignored in the likelihood model.

For other variant callers, I would recommend doing the filtering upstream of PureCN.

**Comment by milkcookie** [comment] 2020-06-02 05:55
ok  thanks,  Markus

**Comment by lima1** [comment] 2020-06-04 13:40
Closing this issue now, feel free to open a new issue when something comes up.

**Closed by lima1** 2020-06-04 13:40 UTC
